### ISSUE TITLE
Increase default word count to 6, set lower limit to 4

### ISSUE THREAD

**Issue by atoponce** [passhelp/passhelp.github.io#1]
I don't know if this repository is still updated or not.

A list of 11,500 unique words provide about 13.5 bits of security per word. At four words, this is only approximately a 54 bit security margin, which is within practical exhaustion for [offline clustered GPU password cracking](https://gist.github.com/epixoip/a83d38f412b4737e99bbef804a270c40). Six words provide approximately 80 bits security, getting it out of range for even [well-funded password cracking attacks](https://twitter.com/TerahashCorp/status/1155128018156892160), but still remains within [practical use for the end-user](https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two).

Also, four words should probably be the lower limit, as three words is a trivial 40 bit security margin, which is within a day's work for [password cracking on CPUs with laptops](https://gist.github.com/atoponce/a7715930ae6eb7d6b487f2f76b57a68d).

**Comment by jpeddicord** [comment]
It's not quite at the forefront of my work queue, but I'm happy to make adjustments. I've made this change and pushed that to the site. Please let me know if you spot anything else amiss.

I'm additionally working through GitHub's reported vulns on the main repository, although I don't believe any of them affect the library or webapp itself (all webpack-related fun). But best to clear that out anyhow.

Thanks!

**Comment by atoponce** [comment]
Sweet! Thanks for the fix!
